// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dataaccess

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int32            `json:"id"`
	PhoneNumber string           `json:"phone_number"`
	FullName    string           `json:"full_name"`
	Password    string           `json:"password"`
	Address     *string          `json:"address"`
	Role        int32            `json:"role"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}
