// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: payment.sql

package dataaccess

import (
	"context"
)

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, code, sender_id, bill_id, contract_id, amount, status,return_request_id
FROM public.payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id int32) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.SenderID,
		&i.BillID,
		&i.ContractID,
		&i.Amount,
		&i.Status,
		&i.ReturnRequestID,
	)
	return i, err
}
