// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: process.sql

package dataaccess

import (
	"context"
)

const createProgressTracking = `-- name: CreateProgressTracking :one
insert INTO PUBLIC.PROCESS_TRACKING(
  actor, action, issued_at, request_id
)
VALUES ($1, $2 , now(), $3)
RETURNING id, actor, action, issued_at, request_id
`

type CreateProgressTrackingParams struct {
	Actor     int32  `json:"actor"`
	Action    string `json:"action"`
	RequestID int32  `json:"request_id"`
}

func (q *Queries) CreateProgressTracking(ctx context.Context, arg CreateProgressTrackingParams) (ProcessTracking, error) {
	row := q.db.QueryRow(ctx, createProgressTracking, arg.Actor, arg.Action, arg.RequestID)
	var i ProcessTracking
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Action,
		&i.IssuedAt,
		&i.RequestID,
	)
	return i, err
}

const getAllProgressTracking = `-- name: GetAllProgressTracking :many
select id, actor, action, issued_at, request_id from PUBLIC.PROCESS_TRACKING
where actor = $1
`

func (q *Queries) GetAllProgressTracking(ctx context.Context, actor int32) ([]ProcessTracking, error) {
	rows, err := q.db.Query(ctx, getAllProgressTracking, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProcessTracking
	for rows.Next() {
		var i ProcessTracking
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.IssuedAt,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgressTrackingByRentalId = `-- name: GetProgressTrackingByRentalId :one
select id, actor, action, issued_at, request_id from PUBLIC.PROCESS_TRACKING
where request_id = $1
`

func (q *Queries) GetProgressTrackingByRentalId(ctx context.Context, requestID int32) (ProcessTracking, error) {
	row := q.db.QueryRow(ctx, getProgressTrackingByRentalId, requestID)
	var i ProcessTracking
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Action,
		&i.IssuedAt,
		&i.RequestID,
	)
	return i, err
}
