// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package dataaccess

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO PUBLIC.USERS
(
    phone_number,
    full_name,
    address,
    password,
    role,
    created_at
) VALUES
(
    $1,$2,$3,$4,$5,now()
)
`

type CreateUserParams struct {
	PhoneNumber string  `json:"phone_number"`
	FullName    string  `json:"full_name"`
	Address     *string `json:"address"`
	Password    string  `json:"password"`
	Role        int32   `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.PhoneNumber,
		arg.FullName,
		arg.Address,
		arg.Password,
		arg.Role,
	)
	return err
}

const getUsers = `-- name: GetUsers :many
SELECT id, phone_number, full_name, password, address, role, created_at, deleted_at 
FROM PUBLIC.USERS
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.FullName,
			&i.Password,
			&i.Address,
			&i.Role,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
