// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: tenants.sql

package dataaccess

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :exec
INSERT INTO "tenants" 
(
  "room_id", 
  "tenant_id", 
  "begin_date", 
  "end_date", 
  "created_at", 
  "updated_at", 
  "deleted_at"
) 
VALUES 
(
  $1, $2, $3, $4, now(), now(), $5
)
`

type CreateTenantParams struct {
	RoomID    int32              `json:"room_id"`
	TenantID  int32              `json:"tenant_id"`
	BeginDate pgtype.Timestamptz `json:"begin_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.Exec(ctx, createTenant,
		arg.RoomID,
		arg.TenantID,
		arg.BeginDate,
		arg.EndDate,
		arg.DeletedAt,
	)
	return err
}
