name: Deploy Smart Rental House Application

on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create config file
        run: |
          mkdir -p configs
          touch configs/local.yaml
          echo '${{ secrets.CONFIG }}' > configs/local.yaml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4.0.0
        with:
          path: /tmp/.buildx-cache/${{ github.event.repository.name }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
          REALEASE_BRANCHS: master
          PRERELEASE: false
          MAJOR_STRING_TOKEN: UPDATE
          MINOR_STRING_TOKEN: update
          TAG_CONTEXT: repo

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/smart-rental:latest,${{ secrets.DOCKER_USERNAME }}/smart-rental:${{ steps.tag.outputs.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache/${{ github.event.repository.name }}/backend
          cache-to: type=local,dest=/tmp/.buildx-cache/${{ github.event.repository.name }}/backend,mode=max

      - name: Build and push image socket
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./socketio/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/smart-rental-socket:latest,${{ secrets.DOCKER_USERNAME }}/smart-rental-socket:${{ steps.tag.outputs.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache/${{ github.event.repository.name }}/socket
          cache-to: type=local,dest=/tmp/.buildx-cache/${{ github.event.repository.name }}/socket,mode=max
  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            export TAG=${{ needs.build-push.outputs.tag }}
            cat docker-compose.yaml.j2 | envsubst > docker-compose.yaml
            sudo docker compose  down
            sudo docker compose up -f docker-compose.yaml -d
