name: Deploy Smart Rental House Application

on: 
    push: 
        branches: 
            - master


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Create .env file
              run: |
                  echo "PORT=${{ secrets.PORT }}" >> .env
                  echo "CONN_STRING=${{ secrets.CONN_STRING }}" >> .env

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Cache Docker layers
              uses: actions/cache@v4.0.0
              with:
                path: /tmp/.buildx-cache/${{ github.event.repository.name }}
                key: ${{ runner.os }}-buildx-${{ github.sha }}
                restore-keys: |
                  ${{ runner.os }}-buildx-
                  
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push image
              uses: docker/build-push-action@v6
              id: status
              with:
                context: .  
                file: Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/smart-rental:latest 
                cache-from: type=local,src=/tmp/.buildx-cache/${{ github.event.repository.name }}
                cache-to: type=local,dest=/tmp/.buildx-cache/${{ github.event.repository.name }},mode=max
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
          - name: Pull docker image
            run: docker pull khanghoang1210/smart-rental:latest
          - name: Delete old container
            run: docker rm -f smart-rental-container
          - name: Run docker container 
            run: docker run -d -p 8080:8080 --name smart-rental-container khanghoang1210/smart-rental